#!/bin/bash
#*****************************************************************
# This Script is for analysis the rate of flow about this system *
# Write by fushijia 2016-01-12 TELL:18591925717			 *
#*****************************************************************
# Defination global value
i=1
# Get the eth model number inuse
ETH_NUMBER=`nmcli d | awk -F ' ' '{print $1}'|sed -n '2p'`
echo "${ETH_NUMBER}"
# Record the path of rx_bytes file
PWD_RX="/sys/class/net/$ETH_NUMBER/statistics/rx_bytes"
# Record the path of tx_bytes file
PWD_TX="/sys/class/net/$ETH_NUMBER/statistics/tx_bytes"
echo "${PWD_RX}"
# Defination the function of rate of Rx_Flow
Function_RxFlow()
{
	RX1=`cat ${PWD_RX}`	
	sleep 1
	RX2=`cat ${PWD_RX}`
	RX=`expr ${RX2} - ${RX1}`
	RX_FLOW=$(echo "scale=2;${RX}/1024"|bc -l|awk '{printf "%.2f",$0}')
	echo  "${RX_FLOW}kb/s	" >> RX_FLOW.dat
}
# Defination the function of rate of Tx_Flow
Function_TxFlow()
{
	TX1=`cat ${PWD_TX}`	
	sleep 1
	TX2=`cat ${PWD_TX}`
	TX=`expr ${TX2} - ${TX1}`
	TX_FLOW=$(echo "scale=2;${TX}/1024"|bc -l|awk '{printf "%.2f",$0}')
	echo  "${TX_FLOW}kb/s	" >> TX_FLOW.dat
}
# Start to calculate in a while loop
while true
do
{	
	#invoke the Function_Flow
	if [ ${i} -lt 10 ]
	then
	{
		#echo "${i}"
		Function_RxFlow
		Function_TxFlow
		#suit for /bin/bash
		((i++))
		#suit for /bin/sh
		#i=$(( ${i} + 1 ))
	}
	else
	{
		Function_RxFlow
		Function_TxFlow
		echo ""
		TIME=1
	}
	fi
}
done
##USED_PERCENT=$(echo "scale=4;${FREE_USED}/${FREE_TOTAL}*100"|bc)
